// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Tornado9966/menu-example/server/menu"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*MenuApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := menu.NewStore(db)
	httpHandlerFunc := menu.HttpHandler(store)
	menuApiServer := &MenuApiServer{
		Port:            port,
		DishesHandler: httpHandlerFunc,
	}
	return menuApiServer, nil
}
